################################################################################
#
# vCenter Setup Section
# VMWare vCenter and the ESXi hosts must be installed and available
# using the IP addresses and passwords provided. The ESXi addresses and
# passwords are part of inventory file. The vCenter connectivity info is
# included in group_vars/all.yml
#
#
################################################################################
- hosts: localhost
#
  roles:
    - VMWAREvcenter

################################################################################
#
# Hosts Setup Section
# If configure_fc is commented out, the host config will be skipped
# If inventory does not contain any servers under esxi_fc section, the config will be skipped
#
################################################################################

- hosts: esxi_fc
  gather_facts: no
  serial: 1
  roles:
    - role: ESXIpostvC
      when: configure_fc is defined
