################################################################################
#
# Hosts Setup Section
# If configure_fc is commented out, the host config will be skipped
# If inventory does not contain any servers under esxi_fc section, the config will be skipped
#
################################################################################
---


- hosts: esxi_fc
  gather_facts: no
  serial: 1
  vars_files:
    - vars/ontap_main.yml
    - group_vars/vcenter.yml
  roles:
    - role: ESXIhosts
      when: configure_fc is defined
