---
# This Playbook uses roles to setup MDS switches
# After executing this playbook, MDS switches should be configured
#
- hosts: mds
  connection: network_cli
  gather_facts: no
  vars_files:
    - vars/ontap_main.yml
  roles:
    ### Configure MDS Switching
    #
    - MDSconfig
