---
# This Playbook uses roles to
# setup Nexus switches
# After executing this playbook, Nexus switches should be configured
#
- hosts: nexus
  connection: network_cli
  gather_facts: no
  roles:
    ### Configure Nexus Switching
    #
    - NEXUSconfig
    #
